import logging

from fastapi import APIRouter, HTTPException, status

from app.models.canonical_patient import ProvenanceRecord
from app.models.workflow_models import MedicationFinding, MedRecRequest, MedRecResponse

router = APIRouter(prefix="/api/medrec", tags=["medrec"])
logger = logging.getLogger(__name__)


def build_medrec_placeholder_response(payload: MedRecRequest) -> MedRecResponse:
    if not payload.patient_id.strip():
        raise ValueError("patient_id must not be empty.")

    findings: list[MedicationFinding] = []
    seen: set[str] = set()

    for medication in payload.medications:
        normalized_name = medication.display.strip().lower()
        if normalized_name in seen:
            findings.append(
                MedicationFinding(
                    category="duplicate_medication",
                    severity="medium",
                    medication_id=medication.medication_id,
                    medication_display=medication.display,
                    rationale="Placeholder duplicate detection matched medication display names.",
                    recommended_action="Review duplicates during medication reconciliation.",
                )
            )
            continue
        seen.add(normalized_name)

    response = MedRecResponse.accepted(
        patient_id=payload.patient_id,
        encounter_id=payload.encounter_id,
        correlation_id=payload.correlation_id,
        message="Medication reconciliation placeholder accepted.",
        normalized_medications=payload.medications,
        findings=findings,
    )
    response.provenance = [
        ProvenanceRecord(
            trace_id=payload.correlation_id,
            agent_name="medrec-route",
            note="Placeholder medication reconciliation response generated by API route.",
        )
    ]
    return response


@router.post("/run", response_model=MedRecResponse, status_code=status.HTTP_202_ACCEPTED)
async def run_medrec(payload: MedRecRequest) -> MedRecResponse:
    try:
        return build_medrec_placeholder_response(payload)
    except ValueError as exc:
        logger.warning("Invalid medrec request: %s", exc)
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(exc)) from exc
    except Exception as exc:
        logger.exception("Unexpected medrec route failure")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Unable to process medication reconciliation request.",
        ) from exc
