import logging

from fastapi import APIRouter, HTTPException, status

from app.models.canonical_patient import ProvenanceRecord
from app.models.workflow_models import TransitionRequest, TransitionResponse

router = APIRouter(prefix="/api/transition", tags=["transition"])
logger = logging.getLogger(__name__)


def build_transition_placeholder_response(payload: TransitionRequest) -> TransitionResponse:
    if not payload.patient_id.strip():
        raise ValueError("patient_id must not be empty.")

    response = TransitionResponse.accepted(
        patient_id=payload.patient_id,
        encounter_id=payload.encounter_id,
        correlation_id=payload.correlation_id,
        message="Transition workflow placeholder accepted.",
        mode=payload.mode,
        summary_text=(
            f"Placeholder {payload.transition_type.value} summary for patient "
            f"{payload.patient_id}."
        ),
        artifacts={
            "transition_type": payload.transition_type.value,
            "requested_outputs": payload.requested_outputs,
            "processing_state": "placeholder",
        },
    )
    response.handoff_sections = {
        "situation": "Placeholder situation summary pending clinical orchestration.",
        "medications": "Placeholder medication handoff content pending reconciliation.",
    }
    response.provenance = [
        ProvenanceRecord(
            trace_id=payload.correlation_id,
            agent_name="transition-route",
            note="Placeholder transition response generated by API route.",
        )
    ]
    return response


@router.post("/run", response_model=TransitionResponse, status_code=status.HTTP_202_ACCEPTED)
async def run_transition(payload: TransitionRequest) -> TransitionResponse:
    try:
        return build_transition_placeholder_response(payload)
    except ValueError as exc:
        logger.warning("Invalid transition request: %s", exc)
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(exc)) from exc
    except Exception as exc:
        logger.exception("Unexpected transition route failure")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Unable to process transition request.",
        ) from exc
